services:
  gohex-api:
    build: .
    environment:
      GOHEX_HOST: 0.0.0.0
      GOHEX_DBHOST: metadata-db
    ports:
      - 8081:8081
  metadata-db:
    build: ./metadata-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=metadata
      - POSTGRES_PASSWORD=dockerized_metadata
    restart: on-failure
