// Code generated by mockery v2.33.0. DO NOT EDIT.

package busmocks

import (
	context "context"

	bus "github.com/adnicolas/golang-hexagonal/kit/bus"

	mock "github.com/stretchr/testify/mock"
)

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

// DispatchCommand provides a mock function with given fields: _a0, _a1
func (_m *Bus) DispatchCommand(_a0 context.Context, _a1 bus.Command) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bus.Command) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DispatchQuery provides a mock function with given fields: _a0, _a1
func (_m *Bus) DispatchQuery(_a0 context.Context, _a1 bus.Query) (bus.QueryResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bus.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bus.Query) (bus.QueryResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bus.Query) bus.QueryResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bus.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bus.Query) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterCommand provides a mock function with given fields: _a0, _a1
func (_m *Bus) RegisterCommand(_a0 bus.Type, _a1 bus.CommandHandler) {
	_m.Called(_a0, _a1)
}

// RegisterQuery provides a mock function with given fields: _a0, _a1
func (_m *Bus) RegisterQuery(_a0 bus.Type, _a1 bus.QueryHandler) {
	_m.Called(_a0, _a1)
}

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bus {
	mock := &Bus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
